Status: Failed
Test Event Name: test

Response:
{
  "errorMessage": "An error occurred (ValidationError) when calling the DetectStackDrift operation: Drift detection is already in progress for stack [arn:aws:cloudformation:us-east-1:158366596870:stack/Team-maintainer-members/34d888d0-e3b0-11ef-9675-0ece30c9efc5]",
  "errorType": "ClientError",
  "requestId": "547fcb9f-63d2-4a6d-8b33-e837c1113a71",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 35, in lambda_handler\n    drift_status = detect_stack_drift(stack_name)\n",
    "  File \"/var/task/lambda_function.py\", line 18, in detect_stack_drift\n    response = cloudformation.detect_stack_drift(StackName=stack_name)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

Function Logs:
START RequestId: 547fcb9f-63d2-4a6d-8b33-e837c1113a71 Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] ClientError: An error occurred (ValidationError) when calling the DetectStackDrift operation: Drift detection is already in progress for stack [arn:aws:cloudformation:us-east-1:158366596870:stack/Team-maintainer-members/34d888d0-e3b0-11ef-9675-0ece30c9efc5]
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 35, in lambda_handler
    drift_status = detect_stack_drift(stack_name)
  File "/var/task/lambda_function.py", line 18, in detect_stack_drift
    response = cloudformation.detect_stack_drift(StackName=stack_name)
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
END RequestId: 547fcb9f-63d2-4a6d-8b33-e837c1113a71
REPORT RequestId: 547fcb9f-63d2-4a6d-8b33-e837c1113a71	Duration: 11709.81 ms	Billed Duration: 11710 ms	Memory Size: 128 MB	Max Memory Used: 85 MB

Request ID: 547fcb9f-63d2-4a6d-8b33-e837c1113a71
